global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'flask_dash_app'
    static_configs:
      - targets: ['10.211.223.102:8050']  # <---- for your local app on macOS
